Simplify deploy scripts.

diff --git a/.deploy/RUN_GENERATE b/.deploy/RUN_GENERATE
--- a/.deploy/RUN_GENERATE
+++ b/.deploy/RUN_GENERATE
@@ -1,14 +1,25 @@
 #!/usr/bin/env bash
 
+#SBATCH --account=sc122-dimitri
+#SBATCH --cpus-per-task=1
+#SBATCH --nodes=1
+#SBATCH --partition=standard
+#SBATCH --qos=standard
+#SBATCH --tasks-per-node=1
+#SBATCH --time=7:00:00
+
 # Exit immediately on errors, treat unset variables as an error, and fail on error in any pipeline
 set -euo pipefail
 
+if [ "$(whoami)" = "dimitri_rusin" ]; then
+  module load anaconda3/2023.09
+  cd /work/sc122/sc122/dimitri_rusin/oll_onemax/
+fi
 
-
-# Dynamically find the Conda executable path
+# Find the path to the conda executable
 conda_path=$(which conda)
 
-# Determine the correct path for conda.sh based on the location of the conda executable
+# Determine the path to conda.sh based on the conda executable location
 if [[ "$conda_path" == */condabin/conda ]]; then
   conda_sh_path="${conda_path%/condabin/conda}/etc/profile.d/conda.sh"
 elif [[ "$conda_path" == */bin/conda ]]; then
@@ -18,12 +29,43 @@ else
   exit 1
 fi
 
-echo "Sourcing: $conda_sh_path"
-# Source the conda.sh script for proper initialization
-source "$conda_sh_path"
+# Source conda.sh if it exists, else export PATH
+if [ -f "$conda_sh_path" ]; then
+  echo "Sourcing: $conda_sh_path"
+  source "$conda_sh_path"
+else
+  echo "Exporting PATH with Conda bin directory"
+  export PATH="${conda_path%/bin/conda}/bin:$PATH"
+fi
 
+# Check for the YAML file path argument
+if [ "$#" -ne 1 ]; then
+  echo "Usage: $0 <yaml_path>"
+  exit 1
+fi
 
+yaml_path="$1"
 
 conda activate .deploy/conda_environment
-source <(python .deploy/apply.py config/dim_50.yaml)
+
+# Generate a temporary file in /tmp
+temp_env_file=$(mktemp /tmp/env.XXXXXX)
+
+# Generate the environment variables and capture them in the temporary file
+python .deploy/apply.py "$yaml_path" > "$temp_env_file"
+
+# Check if the previous command was successful
+if [ $? -ne 0 ]; then
+  echo "Error occurred in apply.py"
+  rm -f "$temp_env_file"
+  exit 1
+fi
+
+# Source the environment variables if the Python script was successful
+source "$temp_env_file"
+
+# Continue with the rest of the script
 python src/generate.py
+
+# Clean up the temporary file
+rm -f "$temp_env_file"
